"""Analyze command for ord-plan."""

from datetime import datetime
from typing import Optional

import click

from ..services.analytics_service import AnalyticsService
from ..serializers.dataframe import DataFrameSerializer
from ..utils.validators import validate_date_format, validate_file_path


@click.command(
    epilog="""
  # Basic usage - analyze entire org file
  ord-plan analyze --file tasks.org --output analysis.pkl

  # Analyze specific date range
  ord-plan analyze --file tasks.org --start 2026-01-01 --end 2026-03-31 \\
             --output q1_analysis.pkl

  # Filter by specific tags
  ord-plan analyze --file tasks.org --tags skill --output skills.pkl
  ord-plan analyze --file tasks.org --tags "chore:payment" --output bills.pkl

  # JSON output format
  ord-plan analyze --file tasks.org --format json --output analysis.json

  # Filter by class UUID
  ord-plan analyze --file tasks.org --class 2e3f6844-e6ec-4e52-bd4e-821de5ba9b8e \\
             --output class_analysis.pkl

 For detailed help with examples, visit: https://github.com/vonpupp/ord-plan
"""
)
@click.option(
    "--file",
    required=True,
    type=click.Path(exists=True, readable=True),
    help="""Path to org-mode file to analyze.

    This file should contain tasks generated by ord-plan with properties
    like CLASS, ACCEPTANCE, and tags.""",
)
@click.option(
    "--start",
    "start_date",
    type=str,
    help="""Start date for analysis.

     Formats: YYYY-MM-DD, today, tomorrow, yesterday, next [day], next
week/month/year, +N days
     Default: Start of file""",
)
@click.option(
    "--end",
    "end_date",
    type=str,
    help="""End date for analysis.

     Formats: YYYY-MM-DD, today, tomorrow, yesterday, next [day], next
week/month/year, +N days
     Default: End of file""",
)
@click.option(
    "--tags",
    "tag_filter",
    type=str,
    help="""Filter tasks by tag.

    Only tasks containing this tag will be included in the analysis.
    For nested tags like :chore:payment:, matches any component.""",
)
@click.option(
    "--class",
    "class_filter",
    type=str,
    help="""Filter tasks by class UUID.

    Only tasks with this CLASS property value will be included.""",
)
@click.option(
    "--format",
    type=click.Choice(["pickle", "json", "csv"]),
    default="pickle",
    help="""Output format for the dataframe.

    - pickle: Binary format, best for streamlit (default)
    - json: Human-readable text format
    - csv: Spreadsheet format""",
)
@click.option(
    "--output",
    "output_path",
    type=click.Path(),
    help="""Path to output file.

    If not specified, output goes to stdout (for pickle/json only).""",
)
def analyze(
    file: str,
    start_date: Optional[str],
    end_date: Optional[str],
    tag_filter: Optional[str],
    class_filter: Optional[str],
    format: str,
    output_path: Optional[str],
) -> None:
    """Analyze org-mode file and extract task data for visualization.

    This command reads an org-mode file generated by ord-plan and extracts
    task data including dates, TODO states, properties, tags, and acceptance
    criteria. The data is exported as a pandas dataframe for use in
    visualization tools like streamlit dashboards.

    The output includes raw data only - compliance calculations and
    visualizations are handled by separate tools.
    """
    # Validate start date if provided
    if start_date:
        errors = validate_date_format(start_date)
        if errors:
            click.echo(f"Error: Invalid start date format: {errors[0]}", err=True)
            raise click.Abort()

    # Validate end date if provided
    if end_date:
        errors = validate_date_format(end_date)
        if errors:
            click.echo(f"Error: Invalid end date format: {errors[0]}", err=True)
            raise click.Abort()

    # Parse dates (use DateService for consistent parsing)
    from ..services.date_service import DateService

    parsed_start = None
    parsed_end = None

    if start_date:
        parsed_start = DateService.parse_date(start_date)
    if end_date:
        parsed_end = DateService.parse_date(end_date)

    # Extract task data using AnalyticsService
    df = AnalyticsService.extract_task_data(
        org_file=file,
        start_date=parsed_start,
        end_date=parsed_end,
        class_filter=class_filter,
        tag_filter=tag_filter,
    )

    if df.empty:
        click.echo("Warning: No tasks found matching the specified criteria", err=True)

    # Prepare metadata
    metadata = {
        "source_file": file,
        "analysis_date": datetime.now().isoformat(),
        "start_date": parsed_start.isoformat() if parsed_start else None,
        "end_date": parsed_end.isoformat() if parsed_end else None,
        "tag_filter": tag_filter,
        "class_filter": class_filter,
        "total_tasks": len(df),
    }

    # Output based on format
    if output_path:
        DataFrameSerializer.serialize(df, output_path, format, metadata)
        click.echo(f"Analysis complete: {len(df)} tasks exported to {output_path}")
    else:
        # Output to stdout (for pickle/json)
        if format == "pickle":
            import pickle
            import sys

            data = {"df": df, "metadata": metadata}
            pickle.dump(data, sys.stdout.buffer)
            # Note: No message for pickle stdout
        elif format == "json":
            import json
            import sys

            data = {
                "data": df.to_dict(orient="records", date_format="iso"),
                "metadata": metadata,
            }
            json.dump(data, sys.stdout, indent=2, default=str)
        else:
            # CSV to stdout
            df.to_csv(sys.stdout, index=False)
            click.echo(f"\n# Analysis complete: {len(df)} tasks")
